# Generated by Django 2.2.12 on 2020-08-07 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('station', models.PositiveSmallIntegerField(choices=[(1, 'Station A'), (2, 'Station B'), (3, 'Station C')])),
                ('start_time', models.DateTimeField()),
                ('stop_time', models.DateTimeField()),
                ('diff', models.DurationField(blank=True, null=True)),
            ],
        ),
    ]
