# Generated by Django 2.2.12 on 2020-08-08 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200808_0158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cage',
            name='diff',
        ),
    ]
