# Generated by Django 2.2.12 on 2020-08-09 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_cage_diff'),
    ]

    operations = [
        migrations.AddField(
            model_name='cage',
            name='diff',
            field=models.DateTimeField(null=True),
        ),
    ]
