# Generated by Django 2.2.12 on 2020-08-09 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200810_0348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cage2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('station1', models.CharField(default='To be updated', max_length=100)),
                ('station2', models.CharField(default='To be updated', max_length=100)),
                ('station3', models.CharField(default='To be updated', max_length=100)),
            ],
        ),
    ]
