# Generated by Django 2.2.12 on 2020-08-09 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200810_0446'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cage2',
        ),
    ]
